### ISSUE TITLE
Request for Installation procedure for Windows

### ISSUE THREAD

**Issue by k0th31** [glumia/openload_dl#1]
Hi boss
please list down step-by-step for Windows users installation.

**Comment by glumia** [comment]
Hi k0th31,
unfortunately the script is based on linux features that aren't portable on windows (xvfb, pyvirtualdisplay).

I did a quick search on the web and I've seen that it shouldn't be difficult to write a more portable version: selenium and requests are already compatible with windows while virtual displays trough pyvirtualdisplay and xvfb are no more necessary because modern browsers support headless mode by default.

I will work on a version that works in both windows and linux in the future. 
Thanks for the advice :)

**Comment by glumia** [comment]
With the last commit (https://github.com/gius-italy/openload-dl/commit/5717888e96b97b10ffb42290a65a6e9f0bb72797) I removed the need of xvfb and pyvirtualdisplay and the script is now compatible with Windows. 

I added a step-by-step installation for windows users. (https://github.com/gius-italy/openload-dl/commit/568878d3c88c944ba642d3c16eef1276e5a927ee)
